#!/bin/sh
#############
# Used to auto launch the api-and-webapp-boilerplate
#
# This script should be moved to /etc/init.d/api
#
# make it an executable with:
# `sudo chmod 755 /etc/init.d/api`
#
# register script to be run at start up
# `sudo update-rc.d api defaults`
#
#############

echo Starting api-and-webapp-boilerplate

set -x on
BASE_DIR =/etc/init.d
export BASE_DIR
cd $BASE_DIR
cd ../../home/pi/api-and-webapp-boilerplate # replace pi with username
sudo npm start